# Generated by Django 5.1 on 2024-08-27 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customer", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="importhistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("import_date", models.DateField(auto_now_add=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("file", models.FileField(upload_to="importdata/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("imported", models.BooleanField(default=False)),
                ("cleaned", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "importhistory",
                "verbose_name_plural": "importhistorys",
                "db_table": "importhistory",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="rawdata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("apptitle", models.CharField(blank=True, max_length=100, null=True)),
                ("case_id", models.CharField(blank=True, max_length=100, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("bodypart", models.CharField(max_length=100)),
                ("modality", models.CharField(max_length=100)),
                ("equipment", models.CharField(max_length=100)),
                (
                    "studydescription",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("imagecount", models.IntegerField(blank=True, null=True)),
                (
                    "accessionnumber",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("readprice", models.FloatField(blank=True, null=True)),
                ("reader", models.CharField(blank=True, max_length=100, null=True)),
                ("approver", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "radiologist",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("studydate", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "approveddttm",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("stat", models.CharField(blank=True, max_length=100, null=True)),
                ("pacs", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "requestdttm",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ecode", models.CharField(blank=True, max_length=100, null=True)),
                ("sid", models.CharField(blank=True, max_length=100, null=True)),
                ("patientid", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cleaned", models.BooleanField(default=False)),
                ("verified", models.BooleanField(default=False)),
                (
                    "importhistory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="importdata.importhistory",
                    ),
                ),
            ],
            options={
                "verbose_name": "rawdata",
                "verbose_name_plural": "rawdatas",
                "db_table": "rawdata",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="cleanData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("apptitle", models.CharField(blank=True, max_length=100, null=True)),
                ("case_id", models.CharField(blank=True, max_length=100, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("bodypart", models.CharField(max_length=100)),
                ("modality", models.CharField(max_length=100)),
                ("equipment", models.CharField(max_length=100)),
                (
                    "studydescription",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("imagecount", models.IntegerField(blank=True, null=True)),
                (
                    "accessionnumber",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("stat", models.CharField(blank=True, max_length=100, null=True)),
                ("readprice", models.FloatField(blank=True, null=True)),
                ("reader", models.CharField(blank=True, max_length=100, null=True)),
                ("approver", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "radiologist",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("studydate", models.CharField(blank=True, max_length=100, null=True)),
                ("studydate_clean", models.DateField(blank=True, null=True)),
                (
                    "approveddttm",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("approveddttm_clean", models.DateTimeField(blank=True, null=True)),
                ("pacs", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "requestdttm",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("requestdttm_clean", models.DateTimeField(blank=True, null=True)),
                ("ecode", models.CharField(blank=True, max_length=100, null=True)),
                ("sid", models.CharField(blank=True, max_length=100, null=True)),
                ("patientid", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "Platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.platform",
                    ),
                ),
                (
                    "approver_clean",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approver_id",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.company",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.contract",
                    ),
                ),
                (
                    "contract_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.contractitem",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.product",
                    ),
                ),
                (
                    "reader_clean",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reader_id",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rawdata",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="importdata.rawdata",
                    ),
                ),
            ],
            options={
                "verbose_name": "cleandata",
                "verbose_name_plural": "cleandatas",
                "db_table": "cleandata",
                "managed": True,
            },
        ),
    ]
