# Generated by Django 5.1 on 2024-08-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
