# Generated by Django 5.1 on 2024-09-09 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_company_clinic_id'),
        ('importdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cleandata',
            options={'managed': True, 'verbose_name': 'cleandata', 'verbose_name_plural': 'cleandata'},
        ),
        migrations.RemoveField(
            model_name='cleandata',
            name='approveddttm_clean',
        ),
        migrations.RemoveField(
            model_name='cleandata',
            name='approver_clean',
        ),
        migrations.RemoveField(
            model_name='cleandata',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='cleandata',
            name='contract_item',
        ),
        migrations.RemoveField(
            model_name='cleandata',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cleandata',
            name='reader_clean',
        ),
        migrations.RemoveField(
            model_name='cleandata',
            name='requestdttm_clean',
        ),
        migrations.RemoveField(
            model_name='cleandata',
            name='studydate_clean',
        ),
        migrations.RemoveField(
            model_name='cleandata',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='cleandata',
            name='amonth',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='cleandata',
            name='ayear',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='cleandata',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cleandata',
            name='Platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.platform'),
        ),
        migrations.AlterField(
            model_name='cleandata',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.company'),
        ),
        migrations.AlterField(
            model_name='cleandata',
            name='imagecount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cleandata',
            name='readprice',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
