# Generated by Django 5.1 on 2024-08-28 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importdata', '0002_alter_rawdata_created_at_alter_rawdata_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='bodypart',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='equipment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='modality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
