# Generated by Django 5.1 on 2024-09-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importdata', '0002_alter_cleandata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleandata',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
