# Generated by Django 5.1 on 2024-08-28 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importdata', '0003_alter_rawdata_bodypart_alter_rawdata_equipment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp_customer_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='temp_doctor_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('doctor_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
