# Generated by Django 5.1 on 2024-09-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importdata', '0003_cleandata_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleandata',
            name='bodypart',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cleandata',
            name='equipment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cleandata',
            name='modality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
