# Generated by Django 5.1 on 2024-09-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importdata', '0004_temp_customer_table_temp_doctor_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apptitle', models.CharField(blank=True, max_length=100, null=True)),
                ('case_id', models.CharField(blank=True, max_length=100, null=True)),
                ('modality', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('approver', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='importhistory',
            name='source_from',
            field=models.CharField(blank=True, choices=[('ONPACS', 'ONPACS'), ('CV3', 'CV3'), ('HPACS', 'HPACS')], max_length=10, null=True),
        ),
    ]
