# Generated by Django 5.1 on 2024-09-30 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importdata', '0004_alter_cleandata_bodypart_alter_cleandata_equipment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleandata',
            name='Platform',
        ),
    ]
