# Generated by Django 5.1 on 2024-09-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importdata', '0005_editeddata_importhistory_source_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importhistory',
            name='source_from',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
