# Generated by Django 5.1 on 2024-09-05 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importdata', '0007_rawdata_amonth_rawdata_ayear'),
    ]

    operations = [
        migrations.AddField(
            model_name='importhistory',
            name='amonth',
            field=models.CharField(blank=True, choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='importhistory',
            name='ayear',
            field=models.CharField(blank=True, choices=[('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026')], max_length=5, null=True),
        ),
    ]
