# Generated by Django 5.1 on 2024-09-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importdata', '0008_importhistory_amonth_importhistory_ayear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importhistory',
            name='source_from',
            field=models.CharField(blank=True, choices=[('ONPACS', 'ONPACS'), ('CV3', 'CV3'), ('HPACS', 'HPACS')], max_length=10, null=True),
        ),
    ]
