# Generated by Django 5.1 on 2024-09-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importdata', '0009_alter_importhistory_source_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_doctor_table',
            name='cv3_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='temp_doctor_table',
            name='department',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='temp_doctor_table',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temp_doctor_table',
            name='fee_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temp_doctor_table',
            name='onpacs_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='temp_doctor_table',
            name='position',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='temp_doctor_table',
            name='specialty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='importhistory',
            name='source_from',
            field=models.CharField(blank=True, choices=[('ONPACS', 'ONPACS'), ('CV3', 'CV3'), ('HPACS', 'HPACS'), ('ETC', 'ETC')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='temp_doctor_table',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
