# Generated by Django 5.1 on 2024-09-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='clinic_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
