# Generated by Django 5.1 on 2024-09-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_company_clinic_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
