# Generated by Django 5.1 on 2024-09-23 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_company_is_public'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='Platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.platform'),
        ),
    ]
