# Generated by Django 5.1 on 2024-09-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_company_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='business_name',
            field=models.CharField(default='Hospital name', max_length=100),
        ),
    ]
