# Generated by Django 5.1 on 2024-09-30 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_company_business_name'),
        ('importdata', '0005_remove_cleandata_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='company',
        ),
        migrations.RemoveField(
            model_name='company',
            name='Platform',
        ),
        migrations.DeleteModel(
            name='ContractItem',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
    ]
