# Generated by Django 5.1 on 2024-09-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_platform_company_remove_company_platform_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='clinic_id',
            new_name='contact_persion',
        ),
        migrations.AddField(
            model_name='company',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
