# Generated by Django 5.1 on 2024-09-30 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_rename_clinic_id_company_contact_persion_company_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='contact_persion',
            new_name='contact_person',
        ),
    ]
