# Generated by Django 5.1 on 2024-09-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_rename_contact_persion_company_contact_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='business_name',
            field=models.CharField(max_length=100),
        ),
    ]
