# Generated by Django 5.1 on 2024-10-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_company_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('Percent', 'Percent'), ('FlatFee', 'Flat Fee')], default='Percent', max_length=20),
        ),
    ]
