# Generated by Django 5.1 on 2024-10-01 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_alter_contract_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='service_fee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.servicefee'),
        ),
        migrations.AddField(
            model_name='servicefee',
            name='rule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
