# Generated by Django 5.1 on 2024-10-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_alter_servicefee_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicefee',
            name='rate',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
