# Generated by Django 5.1 on 2024-11-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_customerlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerlog',
            old_name='created_by',
            new_name='updated_by',
        ),
        migrations.AddField(
            model_name='customerlog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
