# Generated by Django 5.1 on 2024-11-20 14:59

import customer.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_customercontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('file_name', models.CharField(blank=True, max_length=250, null=True)),
                ('file', models.FileField(blank=True, max_length=250, null=True, upload_to=customer.models.upload_customer_files_location)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.company')),
            ],
        ),
    ]
