# Generated by Django 5.1 on 2024-12-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_alter_company_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_collab',
            field=models.BooleanField(default=False),
        ),
    ]
