# Generated by Django 5.1 on 2024-12-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_company_is_collab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='is_collab',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
