# Generated by Django 5.1 on 2025-01-04 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_company_is_tele'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['business_name'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
    ]
