# Generated by Django 5.1 on 2025-01-04 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_alter_company_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['id'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
    ]
