# Generated by Django 5.1 on 2024-08-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product_code', models.CharField(blank=True, max_length=20, null=True)),
                ('modality', models.CharField(choices=[('CT', 'CT'), ('MR', 'MR'), ('CR', 'CR'), ('MG', 'MG'), ('US', 'US')], max_length=2)),
                ('emergency', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
