# Generated by Django 5.1 on 2024-12-02 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0022_alter_company_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred_date', models.DateField()),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_gender', models.CharField(max_length=10)),
                ('patient_phone', models.CharField(max_length=20)),
                ('patient_birthdate', models.DateField()),
                ('illness', models.CharField(max_length=100)),
                ('treatment', models.CharField(max_length=100)),
                ('opinion1', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chart_number', models.CharField(max_length=20)),
                ('manage_number', models.CharField(max_length=20)),
                ('illness2', models.CharField(max_length=100)),
                ('opinion2', models.TextField()),
                ('opinioned_at', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.company')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_status', models.CharField(max_length=20)),
                ('memo', models.CharField(max_length=100)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('refer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collab.refers')),
            ],
        ),
    ]
