# Generated by Django 5.1 on 2024-12-02 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='refers',
            name='chart_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='refers',
            name='illness',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='refers',
            name='illness2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='refers',
            name='manage_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='refers',
            name='opinion2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refers',
            name='opinioned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refers',
            name='patient_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='refers',
            name='patient_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='refers',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='refers',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Requested', '협진요청'), ('Interpreted', '1차판독완료'), ('Cosigned', '2차찬독완료')], max_length=20),
        ),
        migrations.AlterField(
            model_name='refers',
            name='treatment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
