# Generated by Django 5.1 on 2024-12-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0002_alter_refers_chart_number_alter_refers_illness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refers',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refers',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Requested', '검사요청'), ('Scheduled', '검사예약'), ('Cancelled', '검사취소'), ('Interpreted', '1차판독완료'), ('Cosigned', '2차판독완료'), ('Archive', '정산완료')], max_length=20),
        ),
    ]
