# Generated by Django 5.1 on 2024-12-15 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0003_refers_scheduled_at_alter_refers_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='IllnessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('eng_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('eng_name', models.CharField(blank=True, max_length=100, null=True)),
                ('point', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('deleted_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='refers',
            name='collab_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='refers',
            name='readprice',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ReferIllness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('illness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collab.illnesscode')),
                ('refer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collab.refers')),
            ],
        ),
        migrations.CreateModel(
            name='ReferTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readprice', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('refer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collab.refers')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collab.treatmentcode')),
            ],
        ),
    ]
