# Generated by Django 5.1 on 2024-12-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0004_illnesscode_treatmentcode_refers_collab_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illnesscode',
            name='eng_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='illnesscode',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
