# Generated by Django 5.1 on 2024-12-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0005_alter_illnesscode_eng_name_alter_illnesscode_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='illnesscode',
            options={'ordering': ['code'], 'verbose_name': '질병코드', 'verbose_name_plural': '질병코드'},
        ),
        migrations.AddField(
            model_name='treatmentcode',
            name='category1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='treatmentcode',
            name='category2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='treatmentcode',
            name='category3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
