# Generated by Django 5.1 on 2024-12-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0006_alter_illnesscode_options_treatmentcode_category1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code1', models.CharField(blank=True, max_length=100, null=True)),
                ('code2', models.CharField(blank=True, max_length=200, null=True)),
                ('code3', models.CharField(blank=True, max_length=100, null=True)),
                ('code4', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '간단진단',
                'verbose_name_plural': '간단진단',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='treatmentcode',
            options={'ordering': ['code'], 'verbose_name': '행위코드', 'verbose_name_plural': '행위코드'},
        ),
    ]
