# Generated by Django 5.1 on 2024-12-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0007_simplediagnosis_alter_treatmentcode_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refers',
            name='patient_birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
