# Generated by Django 5.1 on 2024-12-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0008_alter_refers_patient_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refers',
            name='referred_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
