# Generated by Django 5.1 on 2024-12-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0010_refersimplediagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refers',
            name='collab_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='refers',
            name='readprice',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
