# Generated by Django 5.1 on 2024-12-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0011_alter_refers_collab_price_alter_refers_readprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplediagnosis',
            name='step',
            field=models.SmallIntegerField(default=0),
        ),
    ]
