# Generated by Django 5.1 on 2024-12-23 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0012_simplediagnosis_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplediagnosis',
            name='is_head',
            field=models.BooleanField(default=False),
        ),
    ]
