# Generated by Django 5.1 on 2024-12-26 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0013_simplediagnosis_is_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='refers',
            name='cosigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
