# Generated by Django 5.1 on 2024-12-27 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0014_refers_cosigned_at'),
        ('customer', '0024_alter_company_is_collab'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyIllnessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.company')),
                ('illness_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collab.illnesscode')),
            ],
            options={
                'ordering': ['illness_code__code'],
            },
        ),
        migrations.CreateModel(
            name='MySimpleDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.company')),
                ('simple_diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collab.simplediagnosis')),
            ],
            options={
                'ordering': ['simple_diagnosis__order'],
            },
        ),
    ]
