# Generated by Django 5.1 on 2024-12-28 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0016_simplediagnosis_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='refer_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('refer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='collab.refers')),
            ],
            options={
                'verbose_name': 'Refer File',
                'verbose_name_plural': 'Refer Files',
            },
        ),
    ]
