# Generated by Django 5.1 on 2024-12-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0017_referfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='refers',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
