# Generated by Django 5.1 on 2024-12-28 22:38

import collab.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0018_refers_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referfile',
            name='file',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to=collab.models.ReferFile.upload_location_refer),
        ),
    ]
