# Generated by Django 5.1 on 2024-12-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0019_alter_referfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refers',
            name='url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
