# Generated by Django 5.1 on 2025-01-08 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0021_refers_refer_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refers',
            old_name='manage_number',
            new_name='radio_doctor',
        ),
    ]
