# Generated by Django 5.1 on 2025-03-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0022_rename_manage_number_refers_radio_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='refers',
            name='opinion3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refers',
            name='opinion4',
            field=models.TextField(blank=True, null=True),
        ),
    ]
