# Generated by Django 5.1 on 2024-09-12 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_company_clinic_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('platform', models.CharField(choices=[('hpacs', 'HPACS'), ('onpacs', 'OnPACS'), ('cv3', 'CV3'), ('etc', 'ETC')], default='', max_length=10)),
                ('ayear', models.CharField(choices=[], max_length=4)),
                ('amonth', models.CharField(choices=[], max_length=2)),
                ('description', models.TextField(blank=True, null=True)),
                ('afile', models.FileField(upload_to='afiles/')),
                ('imported', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apptitle', models.CharField(blank=True, max_length=100, null=True)),
                ('case_id', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('bodypart', models.CharField(blank=True, max_length=100, null=True)),
                ('modality', models.CharField(blank=True, max_length=100, null=True)),
                ('equipment', models.CharField(blank=True, max_length=100, null=True)),
                ('amodality', models.CharField(blank=True, choices=[('mr', 'MR'), ('ct', 'CT'), ('cr', 'CR'), ('mg', 'MG'), ('us', 'US')], max_length=10, null=True)),
                ('studydescription', models.CharField(blank=True, max_length=100, null=True)),
                ('imagecount', models.IntegerField(blank=True, default=0, null=True)),
                ('accessionnumber', models.CharField(blank=True, max_length=100, null=True)),
                ('stat', models.CharField(blank=True, max_length=100, null=True)),
                ('readprice', models.FloatField(blank=True, default=0, null=True)),
                ('reader', models.CharField(blank=True, max_length=100, null=True)),
                ('approver', models.CharField(blank=True, max_length=100, null=True)),
                ('radiologist', models.CharField(blank=True, max_length=100, null=True)),
                ('studydate', models.CharField(blank=True, max_length=100, null=True)),
                ('studydt', models.DateTimeField(auto_now_add=True, null=True)),
                ('approveddttm', models.CharField(blank=True, max_length=100, null=True)),
                ('approvedt', models.DateTimeField(auto_now_add=True, null=True)),
                ('pacs', models.CharField(blank=True, max_length=100, null=True)),
                ('platform', models.CharField(blank=True, choices=[('hpacs', 'HPACS'), ('onpacs', 'OnPACS'), ('cv3', 'CV3'), ('etc', 'ETC')], max_length=20, null=True)),
                ('requestdttm', models.CharField(blank=True, max_length=100, null=True)),
                ('requestdt', models.DateTimeField(auto_now_add=True, null=True)),
                ('ecode', models.CharField(blank=True, max_length=100, null=True)),
                ('sid', models.CharField(blank=True, max_length=100, null=True)),
                ('patientid', models.CharField(blank=True, max_length=100, null=True)),
                ('ayear', models.CharField(blank=True, max_length=5, null=True)),
                ('amonth', models.CharField(blank=True, max_length=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.company')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('uploadhistory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='minibooks.uploadhistory')),
            ],
            options={
                'verbose_name': 'reportmaster',
                'db_table': 'reportmaster',
                'managed': True,
            },
        ),
    ]
