# Generated by Django 5.1 on 2024-09-12 03:48

import utils.base_func
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minibooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmaster',
            name='amodality',
            field=models.CharField(blank=True, choices=utils.base_func.get_amodality_choices, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reportmaster',
            name='platform',
            field=models.CharField(blank=True, choices=utils.base_func.get_platform_choices, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='amonth',
            field=models.CharField(choices=utils.base_func.get_amonth_choices, max_length=2),
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='ayear',
            field=models.CharField(choices=utils.base_func.get_ayear_choices, max_length=4),
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='platform',
            field=models.CharField(choices=utils.base_func.get_platform_choices, default='', max_length=10),
        ),
    ]
