# Generated by Django 5.1 on 2024-09-14 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_company_clinic_id'),
        ('minibooks', '0002_alter_reportmaster_amodality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmaster',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.platform'),
        ),
    ]
