# Generated by Django 5.1 on 2024-09-14 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minibooks', '0003_alter_reportmaster_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportmaster',
            name='platform',
        ),
    ]
