# Generated by Django 5.1 on 2024-09-14 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minibooks', '0004_remove_reportmaster_platform'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmaster',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.platform'),
        ),
    ]
