# Generated by Django 5.1 on 2024-09-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minibooks', '0008_uploadhistorytrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadhistorytrack',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
