# Generated by Django 5.1 on 2024-09-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minibooks', '0010_reportmaster_exelrownum_reportmaster_pay_to_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmaster',
            name='exelrownum',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
