# Generated by Django 5.1 on 2024-09-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minibooks', '0012_rename_exelrownum_reportmaster_excelrownum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadhistory',
            name='afile',
            field=models.FileField(upload_to='upload_to'),
        ),
    ]
