# Generated by Django 5.1 on 2024-09-18 02:42

import minibooks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minibooks', '0013_alter_uploadhistory_afile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadhistory',
            name='afile',
            field=models.FileField(upload_to=minibooks.models.upload_to),
        ),
    ]
