# Generated by Django 5.1 on 2024-09-25 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minibooks', '0020_reportmasterstat_total_revunue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportmasterstat',
            old_name='total_revunue',
            new_name='total_revenue',
        ),
    ]
