# Generated by Django 5.1 on 2024-09-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minibooks', '0021_rename_total_revunue_reportmasterstat_total_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmaster',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
    ]
