# Generated by Django 5.1 on 2024-09-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minibooks', '0022_reportmaster_is_emergency'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmasterstat',
            name='emergency',
            field=models.BooleanField(default=False),
        ),
    ]
