# Generated by Django 5.1 on 2024-09-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minibooks', '0023_reportmasterstat_emergency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportmaster',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='reportmasterstat',
            name='aday',
        ),
        migrations.RemoveField(
            model_name='reportmasterstat',
            name='platform',
        ),
        migrations.AddField(
            model_name='reportmaster',
            name='is_human_outpatient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportmaster',
            name='is_take',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportmasterstat',
            name='give_or_take',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportmasterstat',
            name='human_outpatient',
            field=models.BooleanField(default=False),
        ),
    ]
