# Generated by Django 5.1 on 2024-09-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minibooks', '0024_remove_reportmaster_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='magammaster',
            name='completed_rows',
            field=models.IntegerField(default=0),
        ),
    ]
