# Generated by Django 5.1 on 2024-09-30 19:02

import django.db.models.deletion
import utils.base_func
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_company_business_name'),
        ('minibooks', '0025_magammaster_completed_rows'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportMasterPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ayear', models.CharField(max_length=4, verbose_name='년도')),
                ('amonth', models.CharField(max_length=2, verbose_name='월')),
                ('amodality', models.CharField(choices=utils.base_func.get_amodality_choices, max_length=10, verbose_name='Modality')),
                ('time_range', models.CharField(max_length=20, verbose_name='TimeRange')),
                ('frequency', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.company', verbose_name='병원명')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='의사명')),
            ],
        ),
    ]
