# Generated by Django 5.1 on 2024-10-01 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_alter_servicefee_rate'),
        ('minibooks', '0026_reportmasterperformance'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagamAccounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ayear', models.CharField(max_length=4, verbose_name='년도')),
                ('amonth', models.CharField(max_length=2, verbose_name='월')),
                ('account_code', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=50)),
                ('account_memo', models.CharField(max_length=200)),
                ('account_total', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='customer.company', verbose_name='거래처')),
            ],
        ),
    ]
