# Generated by Django 5.1 on 2024-10-01 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_alter_servicefee_rate'),
        ('minibooks', '0027_magamaccounting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='magamaccounting',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider', to=settings.AUTH_USER_MODEL, verbose_name='의사'),
        ),
        migrations.AlterField(
            model_name='magamaccounting',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='customer.company', verbose_name='거래처'),
        ),
    ]
