# Generated by Django 5.1 on 2024-10-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minibooks', '0028_magamaccounting_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmaster',
            name='human_paid_all',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reportmaster',
            name='is_human_paid',
            field=models.BooleanField(default=False),
        ),
    ]
