# Generated by Django 5.1 on 2024-10-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minibooks', '0029_reportmaster_human_paid_all_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='magammaster',
            name='is_opened',
            field=models.BooleanField(default=False),
        ),
    ]
