# Generated by Django 5.1 on 2024-10-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minibooks', '0030_magammaster_is_opened'),
    ]

    operations = [
        migrations.AddField(
            model_name='magammaster',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportmaster',
            name='company_paid',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='reportmaster',
            name='human_paid',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
