# Generated by Django 5.1 on 2024-10-25 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minibooks', '0031_magammaster_is_locked_reportmaster_company_paid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmaster',
            name='is_rework',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ReportMasterComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reportmaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minibooks.reportmaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
