# Generated by Django 5.1 on 2024-11-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minibooks', '0032_reportmaster_is_rework_reportmastercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmaster',
            name='ein',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
