# Generated by Django 5.1 on 2024-11-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minibooks', '0033_reportmaster_ein'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmaster',
            name='radiologist_license',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
