# Generated by Django 5.1 on 2024-11-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minibooks', '0034_reportmaster_radiologist_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmaster',
            name='adate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
