# Generated by Django 5.1 on 2025-01-03 02:33

import django.db.models.deletion
import utils.base_func
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_company_is_tele'),
        ('minibooks', '0037_reportmasterstat_total_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportMasterWeekday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ayear', models.CharField(max_length=4, verbose_name='년도')),
                ('amonth', models.CharField(max_length=2, verbose_name='월')),
                ('adate', models.DateField(blank=True, null=True)),
                ('weekday_number', models.SmallIntegerField()),
                ('amodality', models.CharField(choices=utils.base_func.get_amodality_choices, max_length=10, verbose_name='Modality')),
                ('total_count', models.IntegerField(default=0)),
                ('UploadHistory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minibooks.uploadhistory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.company')),
            ],
        ),
    ]
