# Generated by Django 5.1 on 2025-04-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minibooks', '0038_reportmasterweekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmaster',
            name='specialty2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
