# Generated by Django 5.1 on 2025-04-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minibooks', '0039_reportmaster_specialty2'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmaster',
            name='child',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
