# Generated by Django 5.1 on 2024-09-11 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_cv3_id_profile_email_profile_fee_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='specialty3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
