# Generated by Django 5.1 on 2024-09-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_specialty3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='specialty2',
            field=models.CharField(blank=True, choices=[('복부비뇨', '복부/비뇨생식기'), ('신경두경', '신경두경부'), ('흉부심장', '흉부심장'), ('심잘혈관', '심장혈관'), ('근골격', '근골격'), ('유방갑상', '유방/갑상선'), ('소아', '소아'), ('인터벤션', '인터벤션'), ('정형외과', '정형외과')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='specialty3',
            field=models.CharField(blank=True, choices=[('복부비뇨', '복부/비뇨생식기'), ('신경두경', '신경두경부'), ('흉부심장', '흉부심장'), ('심잘혈관', '심장혈관'), ('근골격', '근골격'), ('유방갑상', '유방/갑상선'), ('소아', '소아'), ('인터벤션', '인터벤션'), ('정형외과', '정형외과')], max_length=30, null=True),
        ),
    ]
