# Generated by Django 5.1 on 2024-09-12 03:41

import utils.base_func
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_specialty2_alter_profile_specialty3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='specialty2',
            field=models.CharField(blank=True, choices=utils.base_func.get_specialty_choices, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='specialty3',
            field=models.CharField(blank=True, choices=utils.base_func.get_specialty_choices, max_length=30, null=True),
        ),
    ]
