# Generated by Django 5.1 on 2024-11-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_holidays_productiontarget_workhours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidays',
            name='holiday_date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holidays',
            name='holiday_date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='work_hour',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='work_weekday',
            field=models.CharField(blank=True, choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], max_length=1, null=True),
        ),
    ]
