# Generated by Django 5.1 on 2024-11-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_holidays_holiday_date_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhours',
            name='work_hour',
            field=models.JSONField(default=list),
        ),
    ]
