# Generated by Django 5.1 on 2024-11-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_workhours_work_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidays',
            name='hoiiday_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
