# Generated by Django 5.1 on 2024-11-08 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_holidays_hoiiday_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holidays',
            old_name='hoiiday_date',
            new_name='hoiidays',
        ),
    ]
