# Generated by Django 5.1 on 2024-11-09 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_holidays_hoiidays'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holidays',
            old_name='hoiidays',
            new_name='holidays',
        ),
    ]
