# Generated by Django 5.1 on 2024-11-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_hoiidays_holidays_holidays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_doctor',
            field=models.BooleanField(default=False, verbose_name='Is Doctor'),
        ),
    ]
