# Generated by Django 5.1 on 2024-11-12 04:02

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_customuser_is_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productiontarget',
            name='term_category',
        ),
        migrations.AddField(
            model_name='productiontarget',
            name='max_value',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productiontarget',
            name='work_weekday',
            field=models.CharField(blank=True, choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='contract_status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('T', 'Terminated')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='productiontarget',
            name='target_value',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='HRFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('file_name', models.CharField(max_length=30)),
                ('file', models.FileField(blank=True, null=True, upload_to=accounts.models.upload_location)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
