# Generated by Django 5.1 on 2024-11-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_productiontarget_term_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrfiles',
            name='file_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='hrfiles',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
