# Generated by Django 5.1 on 2024-11-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_hrfiles_file_name_alter_hrfiles_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrfiles',
            name='file_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
