# Generated by Django 5.1 on 2024-11-12 16:06

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_hrfiles_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrfiles',
            name='file',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to=accounts.models.upload_location),
        ),
    ]
