# Generated by Django 5.1 on 2024-11-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_hrfiles_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productiontarget',
            name='work_weekday',
            field=models.CharField(blank=True, choices=[('0', 'Sunday'), ('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contract_status',
            field=models.CharField(choices=[('A', 'Active'), ('P', 'PartTime'), ('I', 'Inactive'), ('T', 'Terminated')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='work_weekday',
            field=models.CharField(blank=True, choices=[('0', 'Sunday'), ('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday')], max_length=1, null=True),
        ),
    ]
