# Generated by Django 5.1 on 2024-12-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_feehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='menu_id',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
