# Generated by Django 5.1 on 2024-11-15 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0015_company_customuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_operator', models.CharField(blank=True, max_length=10, null=True)),
                ('specialty2', models.CharField(blank=True, max_length=30, null=True)),
                ('amodality', models.CharField(blank=True, max_length=10, null=True)),
                ('bodypart', models.CharField(blank=True, max_length=50, null=True)),
                ('memo', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.company')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_source', models.CharField(blank=True, max_length=50, null=True)),
                ('referral_code', models.CharField(blank=True, max_length=10, null=True)),
                ('referred_by', models.CharField(blank=True, max_length=50, null=True)),
                ('referred_to', models.CharField(blank=True, max_length=50, null=True)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('modality', models.CharField(blank=True, max_length=50, null=True)),
                ('amodality', models.CharField(blank=True, max_length=10, null=True)),
                ('bodypart', models.CharField(blank=True, max_length=50, null=True)),
                ('specialty2', models.CharField(blank=True, max_length=30, null=True)),
                ('case_id', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_emergency', models.BooleanField(default=False)),
                ('referral_status_from_source', models.CharField(blank=True, max_length=50, null=True)),
                ('referral_status_from_referdex', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.company')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referdex.referral')),
            ],
        ),
    ]
