# Generated by Django 5.1 on 2024-11-18 01:17

import utils.base_func
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referdex', '0002_productionmade_productionmadedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionmadedetail',
            name='modality',
            field=models.CharField(blank=True, choices=utils.base_func.get_amodality_choices, max_length=10, null=True),
        ),
    ]
