# Generated by Django 5.1 on 2024-11-18 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referdex', '0003_productionmadedetail_modality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionmadedetail',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='referdex.productionmade'),
        ),
    ]
