# Generated by Django 5.1 on 2024-11-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referdex', '0004_alter_productionmadedetail_production'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchrules',
            name='match_operator',
            field=models.CharField(blank=True, choices=[('1', '전담'), ('-1', '거부'), ('0', '기본값')], default='0', max_length=10, null=True),
        ),
    ]
