# Generated by Django 5.1 on 2024-11-18 14:08

import utils.base_func
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referdex', '0005_alter_matchrules_match_operator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchrules',
            name='amodality',
        ),
        migrations.RemoveField(
            model_name='matchrules',
            name='specialty2',
        ),
        migrations.RemoveField(
            model_name='matchrules',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='matchrules',
            name='modality',
            field=models.CharField(blank=True, choices=utils.base_func.get_amodality_choices, max_length=10, null=True),
        ),
    ]
