# Generated by Django 5.1 on 2025-01-04 22:55

import utils.base_func
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referdex', '0007_team_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='specialty',
            field=models.CharField(blank=True, choices=utils.base_func.get_specialty_choices, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
