# Generated by Django 5.1 on 2024-10-03 21:54

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='afile',
            field=models.FileField(blank=True, null=True, upload_to=blog.models.upload_location),
        ),
    ]
