# Generated by Django 5.1 on 2024-10-04 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_afile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Degree', '학위증'), ('Certificate', '인증서')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='200 characters max', max_length=200),
        ),
    ]
