# Generated by Django 5.1 on 2024-10-04 01:48

import utils.base_func
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=utils.base_func.get_blog_category, default='1', max_length=50),
        ),
    ]
