# Generated by Django 5.1 on 2024-10-16 05:20

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_is_deleted_post_is_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postattachment',
            name='file',
            field=models.FileField(upload_to=blog.models.upload_location_public),
        ),
    ]
