# Generated by Django 5.1 on 2024-12-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_opportunity_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chance',
            name='stage',
            field=models.CharField(choices=[('Potential', 'Potential'), ('Qualified', 'Qualified'), ('Working', 'Working'), ('Won', 'Won'), ('Pending', 'Pending'), ('Lost', 'Lost')], max_length=20),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('Potential', 'Potential'), ('Qualified', 'Qualified'), ('Working', 'Working'), ('Won', 'Won'), ('Pending', 'Pending'), ('Lost', 'Lost')], max_length=20),
        ),
        migrations.AlterField(
            model_name='opportunityhistory',
            name='stage',
            field=models.CharField(choices=[('Potential', 'Potential'), ('Qualified', 'Qualified'), ('Working', 'Working'), ('Won', 'Won'), ('Pending', 'Pending'), ('Lost', 'Lost')], max_length=20),
        ),
    ]
