# Generated by Django 5.1 on 2024-09-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_name', models.CharField(max_length=20)),
                ('choice_key', models.CharField(max_length=20)),
                ('choice_value', models.CharField(max_length=20)),
                ('choice_order', models.IntegerField()),
            ],
            options={
                'verbose_name': 'choicemaster',
                'verbose_name_plural': 'choicemasters',
                'db_table': 'choicemaster',
                'managed': True,
            },
        ),
    ]
